lang: eng
dynamic-boxes:
#format: 
#   - [MATERIAL NAME],[CHANCE TO APPEAR OUT OF 100]
# Do not use numeric IDs.
# Search spigot material to find list of material names
# Check console if plugin fails to startup due to a config change
    default:
    - IRON_CHESTPLATE,10
    - DIRT,100
    - DIRT,100
    - IRON_INGOT,15
    - DIRT,30
    - COBBLESTONE,67
    - COBBLESTONE,57